# Generated by Django 4.2.4 on 2023-08-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Han",
            fields=[
                ("han_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "han_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="han_post",
                        to="post.post",
                    ),
                ),
                (
                    "han_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="han_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        related_name="han_like", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HanCom",
            fields=[
                ("hancom_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "hancom_han",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hancom_han",
                        to="han.han",
                    ),
                ),
                (
                    "hancom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hancom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
