# Generated by Django 4.2.4 on 2023-08-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("han", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hancom",
            name="mention",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
