# Generated by Django 4.2.4 on 2023-08-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("line", "0002_alter_question_vote_postsec"),
        ("post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("vote_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=400)),
                ("item1", models.CharField(max_length=400)),
                ("item2", models.CharField(max_length=400)),
                ("item3", models.CharField(max_length=400)),
                ("is_done", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("done_date", models.DateTimeField(default=None, null=True)),
                (
                    "vote_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_line",
                        to="line.line",
                    ),
                ),
                (
                    "vote_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_post",
                        to="post.post",
                    ),
                ),
                (
                    "vote_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_postsec",
                        to="post.postsec",
                    ),
                ),
                (
                    "vote_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vote_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotePer",
            fields=[
                ("voteper_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "age",
                    models.IntegerField(
                        choices=[
                            (1, "10대"),
                            (2, "20대"),
                            (3, "30대"),
                            (4, "40대"),
                            (5, "50대 이상"),
                        ]
                    ),
                ),
                ("select", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                (
                    "voteper_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voteper_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voteper_vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voteper_vote",
                        to="vote.vote",
                    ),
                ),
            ],
        ),
    ]
