# Generated by Django 4.2.4 on 2023-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="done_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
