# Generated by Django 4.2.4 on 2023-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_alter_vote_done_date_alter_vote_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteper",
            name="age",
            field=models.IntegerField(
                choices=[(1, "10대"), (2, "20대"), (3, "30대"), (4, "40대"), (5, "50대 이상")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voteper",
            name="select",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
    ]
