# Generated by Django 4.2.4 on 2023-08-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("post", "0001_initial"),
        ("line", "0002_alter_question_vote_postsec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debate",
            fields=[
                ("debate_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=400)),
                ("num", models.IntegerField()),
                (
                    "cond",
                    models.IntegerField(choices=[(1, "모집중"), (2, "진행중"), (3, "완료")]),
                ),
                (
                    "debate_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_line",
                        to="line.line",
                    ),
                ),
                (
                    "debate_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_postsec",
                        to="post.postsec",
                    ),
                ),
                (
                    "debate_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debate_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debaters",
                    models.ManyToManyField(
                        related_name="debaters", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
