# Generated by Django 4.2.4 on 2023-08-10 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("debate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debate",
            name="cons",
            field=models.ManyToManyField(
                related_name="cons", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="debate",
            name="pros",
            field=models.ManyToManyField(
                related_name="pros", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
