# Generated by Django 3.0.8 on 2023-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_debate_cons_debate_pros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='debaters',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='num',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='pros',
        ),
        migrations.AlterField(
            model_name='debate',
            name='cond',
            field=models.IntegerField(choices=[(1, '진행중'), (2, '완료')], default=1),
        ),
    ]
