# Generated by Django 3.0.8 on 2023-08-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_debate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
