# Generated by Django 4.2.4 on 2023-08-03 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                ("line_id", models.AutoField(primary_key=True, serialize=False)),
                ("sentence", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "line_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_post",
                        to="post.post",
                    ),
                ),
                (
                    "line_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_postsec",
                        to="post.postsec",
                    ),
                ),
                (
                    "line_user",
                    models.ManyToManyField(
                        related_name="line_user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineCom",
            fields=[
                ("linecom_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "like",
                    models.ManyToManyField(
                        related_name="linecom_like", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "linecom_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linecom_line",
                        to="line.line",
                    ),
                ),
                (
                    "linecom_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linecom_postsec",
                        to="post.postsec",
                    ),
                ),
                (
                    "linecom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linecom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("que_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("num", models.IntegerField()),
                (
                    "que_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="que_line",
                        to="line.line",
                    ),
                ),
                (
                    "que_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="que_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vote_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_postsec",
                        to="post.postsec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineComCom",
            fields=[
                ("linecomcom_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "linecomcom_lineCom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linecomcom_lineCom",
                        to="line.linecom",
                    ),
                ),
                (
                    "linecomcom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linecomcom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emotion",
            fields=[
                ("emo_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.IntegerField(
                        choices=[
                            (1, "happy"),
                            (2, "surprise"),
                            (3, "angry"),
                            (4, "sad"),
                            (5, "serious"),
                        ]
                    ),
                ),
                (
                    "emo_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emo_line",
                        to="line.line",
                    ),
                ),
                (
                    "emo_postsec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emo_postsec",
                        to="post.postsec",
                    ),
                ),
                (
                    "emo_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emo_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("ans_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "ans_que",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ans_que",
                        to="line.question",
                    ),
                ),
                (
                    "ans_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ans_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
