# Generated by Django 4.2.4 on 2023-08-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        ("line", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="vote_postsec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="que_postsec",
                to="post.postsec",
            ),
        ),
    ]
