# Generated by Django 4.2.4 on 2023-08-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0003_alter_linecom_linecom_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linecom",
            name="linecom_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linecom_line",
                to="line.line",
            ),
        ),
    ]
