# Generated by Django 4.2.4 on 2023-08-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0004_alter_linecom_linecom_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="vote_postsec",
            new_name="que_postsec",
        ),
    ]
