# Generated by Django 4.2.4 on 2023-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0006_alter_question_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
