# Generated by Django 4.2.4 on 2023-08-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0007_alter_question_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="num",
        ),
    ]
