# Generated by Django 4.2.4 on 2023-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0008_remove_question_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="linecomcom",
            name="mention",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
