# Generated by Django 4.2.4 on 2023-08-03 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follow",
            field=models.ManyToManyField(
                null=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
