# Generated by Django 4.2.4 on 2023-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_follow_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                choices=[(1, "10대"), (2, "20대"), (3, "30대"), (4, "40대"), (5, "50대 이상")],
                null=True,
            ),
        ),
    ]
