# Generated by Django 4.2.4 on 2023-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.TextField(blank=True, null=True),
        ),
    ]
