# Generated by Django 4.2.4 on 2023-08-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
