# Generated by Django 4.2.4 on 2023-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_rename_user_id_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
