# Generated by Django 4.2.4 on 2023-08-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
