# Generated by Django 3.0.8 on 2023-08-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230817_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
