# Generated by Django 4.2.4 on 2023-08-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_alter_user_age"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(verbose_name="date published")),
                (
                    "post_image",
                    models.ImageField(blank=True, null=True, upload_to="post_image"),
                ),
                (
                    "diff",
                    models.IntegerField(
                        choices=[(1, "light"), (2, "middle"), (3, "heavy")]
                    ),
                ),
                (
                    "bookmark",
                    models.ManyToManyField(
                        related_name="post_like", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("hashtag", models.ManyToManyField(to="account.hashtag")),
                (
                    "post_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostSec",
            fields=[
                ("sec_id", models.AutoField(primary_key=True, serialize=False)),
                ("num", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "sec_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sec_post",
                        to="post.post",
                    ),
                ),
            ],
        ),
    ]
