# Generated by Django 4.2.4 on 2023-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(verbose_name="date published"),
        ),
    ]
